### PR TITLE
Added AGPLv3 License

### PR DESCRIPTION
**Pull request by ExtraGravity**
Added AGPLv3 license and put a permission statement at the top of every source file. Please take a close look at this one Jordan, I merged your headers (concerning OLEDs and stuff) with the one I was using, let me know if you think the changes are merges with you.

### CODE REVIEW

**Comment by JordanHeinrichs** [comment]
I will wait to merge this in until everyone has weighed on the other thread about what we want to do about licenses and whatnot. But why did you choose AGPLv3 over GPLv3? The only thing AGPL changes from GPL is that the code must be available if you run it on a server. This is a microcontroller project, there is no risk of this running on a server. 

For the server code I would recommend that being AGPL but for something like this I would just recommend the BSD since we don't need to worry about this coding being used by propitiatory projects. We just want to make sure everything stays open source and we have a claim of no warranty if something happens.

**Comment by ExtraGravity** [comment]
I wanted to pick one license for all the repos for simplicity. But I would agree, BSD would suffice for this project. Along that reasoning, do you want me to change the license to BSD for CCS?

**Comment by JordanHeinrichs** [comment]
I think so, overall I think it is important to use the license that best suits the project. I think that is more important than having one license for everything on the team. AGPL works great for the server project (although not like BSD would be bad for it) but for this project I just don't think it would suit it.

**Comment by ExtraGravity** [comment]
I've changed the license to GPL instead of AGPL. I decided to use GPL instead of BSD because it is more inline with the rest of our projects. And also it was easier to change :P

**Comment by JordanHeinrichs** [comment]
Merged it in, Note that the mbed code under here is actually under the Apache license. But I am pretty sure that license doesn't conflict with GPL.

**Pull request merged**
